# Generated by Django 4.0.1 on 2022-01-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_livro', models.CharField(max_length=200)),
                ('editora_do_livro', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('estrelas', models.IntegerField()),
                ('situacao', models.CharField(blank=True, max_length=100)),
                ('opiniao', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
