# Generated by Django 4.0.1 on 2022-01-07 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerenciador_de_livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='genero',
            new_name='generos',
        ),
    ]
