# Generated by Django 4.0.1 on 2022-01-07 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerenciador_de_livros', '0002_rename_genero_livros_generos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='estrelas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
