# Generated by Django 4.0.1 on 2022-01-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerenciador_de_livros', '0008_alter_livros_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='situacao',
        ),
    ]
