# Generated by Django 4.0.1 on 2022-01-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerenciador_de_livros', '0009_remove_livros_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=10)),
            ],
        ),
    ]
