# Generated by Django 4.0.1 on 2022-01-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerenciador_de_livros', '0011_livros_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='foto_do_livro',
            field=models.ImageField(blank=True, upload_to='imagens/%d/%m'),
        ),
    ]
