# Generated by Django 4.0.1 on 2022-02-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerenciador_de_livros', '0012_livros_foto_do_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='generos',
            field=models.TextField(choices=[('Ficção', 'Ficcao'), ('Ação e aventura', 'Acao E Aventura'), ('Infantil', 'Infantil'), ('Ficção Cristã', 'Ficcao Crista'), ('Clássicos', 'Classicos'), ('Quadrinhos', 'Quadrinhos'), ('Ficção Contemporânea', 'Ficcao Contemp'), ('Fantasia', 'Fantasia'), ('Ficção Histórica', 'Ficcao Historica'), ('Ficção Literária', 'Ficcao Literaria')], max_length=50),
        ),
    ]
