# Generated by Django 4.0.1 on 2022-02-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerenciador_de_livros', '0013_alter_livros_generos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='generos',
            field=models.TextField(choices=[('Ficção', 'Ficcao'), ('Não-ficção', 'Nao Ficcao'), ('Ação e aventura', 'Acao E Aventura'), ('Infantil', 'Infantil'), ('Ficção Cristã', 'Ficcao Crista'), ('Clássicos', 'Classicos'), ('Quadrinhos', 'Quadrinhos'), ('Ficção Contemporânea', 'Ficcao Contemp'), ('Fantasia', 'Fantasia'), ('Ficção Histórica', 'Ficcao Historica'), ('Ficção Literária', 'Ficcao Literaria'), ('Mistério e Crime', 'Misterio'), ('Peças e Roteiros', 'Pecas Roteiros'), ('Poesia', 'Poesia'), ('Romance', 'Romance'), ('Romance contemporâneo', 'Romance Contemp'), ('Romance histórico', 'Romance Historico'), ('Romance Policial', 'Romance Policial'), ('Suspense Romântico', 'Suspense Romantico'), ('Ficção Científica', 'Ficcao Cientifica'), ('Contos', 'Contos'), ('Suspense', 'Suspense'), ('Horror', 'Horror'), ('Biografias e Memórias', 'Biografia'), ('Jovem-Adulto', 'Jovem Adulto'), ('Infanto-Juvenil', 'Infanto Juvenil'), ('Autobiografia', 'Autobio'), ('Tecnologia', 'Tecnologia'), ('Culinária', 'Culinaria'), ('Educação', 'Educacao'), ('Saúde e Bem-estar', 'Saude'), ('Arte', 'Arte'), ('História', 'Historia'), ('Lei', 'Lei'), ('Música', 'Musica'), ('Filosofia', 'Filosofia'), ('Psicologia', 'Psicologia'), ('Sociologia', 'Sociologia'), ('Matemática', 'Matematica'), ('Religião e Espiritualidade', 'Religiao'), ('Autoajuda', 'Autoajuda'), ('Esportes', 'Esportes'), ('Crime Verdadeiro', 'Crime Verdadeiro'), ('Romance Sobrenatural', 'Romance Sobrenatural'), ('Chick-Lit', 'Chick Lit'), ('Épico/Aventura', 'Epico'), ('Distopia', 'Distopia'), ('Sick-Lit', 'Sick Lit')], max_length=50),
        ),
    ]
