# Generated by Django 4.0.1 on 2022-02-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerenciador_de_livros', '0014_alter_livros_generos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='opiniao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
