# Generated by Django 4.0.1 on 2022-02-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gerenciador_de_livros', '0015_alter_livros_opiniao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='opiniao',
            field=models.TextField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
